defi_page_homepage:
    path:     /
    defaults: { _controller: DefiPageBundle:Main:index }

defi_page_search_results:
    path:     /page/results
    defaults: { _controller: DefiPageBundle:Main:searchResults }
    
defi_page_ajax_load_chapters_by_book:
    path : /book/{bookId}/chapters
    defaults: { _controller: DefiPageBundle:Ajax:loadingChaptersByBook }
    
defi_page_ajax_load_verses_by_chapter:
    path : /book/{bookId}/chapter/{chapterId}/verses/{verseStart}
    defaults: { _controller: DefiPageBundle:Ajax:loadingVersesByChapter , verseStart : 1}
    
defi_page_bible_search_results:
    path:     /{bookName}-{bookId}/{chapter}/{verseStart}/{verseEnd}
    defaults: { _controller: DefiPageBundle:Main:bibleSearchResult }    
    requirements:
        bookName:    '[a-zA-Z0-9\-^]+'
        
defi_page_search :
    path: /search
    defaults: { _controller: DefiPageBundle:Main:search }
