services:
    defi.form.type.bible_search:
        class: Defi\PageBundle\Type\BibleSearchType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
