defi_manager:
    resource: "@DefiManagerBundle/Resources/config/routing.yml"
    prefix:   /manager

defi_page:
    resource: "@DefiPageBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"